Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.provision "shell", inline: "apt-get install -y gpg"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
  end
end
